version: '2'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - activemq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/employeedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_ACTIVEMQ_BROKER-URL=tcp://activemq:61616
      - SPRING_ACTIVEMQ_USER=admin
      - SPRING_ACTIVEMQ_PASSWORD=admin
      - SPRING_ACTIVEMQ_PACKAGES_TRUST-all=true

  activemq:
    image: webcenter/activemq
    restart: always
    ports:
      - 61616:61616
      - 8161:8161
    depends_on:
      - postgresql

  postgresql:
    image: 'postgres'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=employeedb